services:
  mariadb:
    image: mariadb
    container_name: leaderboard-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: leaderboard_app
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
      MARIADB_ROOT_PASSWORD: root_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
